pool:
  vmImage: 'Ubuntu-18.04'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: 14
- bash: |
    set -o errexit -o pipefail
    npm ci
    npm run lint
    npm test -- --coverage --coverageReporters=cobertura
  displayName: "Lint & test"
- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
