trigger:
    - main
pool:
    vmImage: 'ubuntu-latest'
variables:
    - group: wayland
steps:
    - task: NodeTool@0
      inputs:
          versionSpec: 18
    - script: |
          set -o errexit -o pipefail
          npm ci
          npm run check
          npm run generate-types
          npm test -- --coverage --coverageReporters=cobertura
          npx esbuild scripts/nordic-publish.ts --bundle --outfile=scripts/nordic-publish.js --platform=node --log-level=warning --minify
          node scripts/esbuild-bootstrap.js
          npm pack
      displayName: 'Build, Test, Compile and Pack'
    - bash: |
          set -o errexit -o pipefail
          cp *.tgz "$(Build.ArtifactStagingDirectory)"
          #Leave for now, testing purposes.
          #condition: ne(variables['Build.Reason'], 'PullRequest')
      displayName: 'Copy Artifacts'
    - task: PublishCodeCoverageResults@1
      displayName: Publish code coverage
      inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
    - task: PublishPipelineArtifact@1
      inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          publishLocation: 'pipeline'
      displayName: 'Publish artifacts to artifact storage'
